package com.androidengineers.agent_quickstart_android.ui.theme

import androidx.compose.ui.graphics.Color

val BetterSaidInk = Color(0xFF1B1C19)
val BetterSaidInkSoft = Color(0xFF444748)
val BetterSaidPaper = Color(0xFFFBF9F4)
val BetterSaidPaperDim = Color(0xFFDBDAD5)
val BetterSaidPaperLow = Color(0xFFF5F3EE)
val BetterSaidPaperMid = Color(0xFFF0EEE9)
val BetterSaidPaperHigh = Color(0xFFEAE8E3)
val BetterSaidPaperHighest = Color(0xFFE4E2DD)
val BetterSaidWhite = Color(0xFFFFFFFF)
val BetterSaidOutline = Color(0xFF747878)
val BetterSaidOutlineSoft = Color(0xFFC4C7C7)

val BetterSaidSage = Color(0xFF4A654E)
val BetterSaidSageSoft = Color(0xFFC9E8CB)
val BetterSaidSageFixed = Color(0xFFCCEACE)
val BetterSaidCoral = Color(0xFFE98074)
val BetterSaidCoralDeep = Color(0xFF7C2C25)
val BetterSaidCoralSoft = Color(0xFFFFDAD5)
val BetterSaidSky = Color(0xFF7BB7D8)
val BetterSaidSkySoft = Color(0xFFD8EDF6)
val BetterSaidYellow = Color(0xFFF3C85B)
val BetterSaidYellowSoft = Color(0xFFFFF0BD)
val BetterSaidError = Color(0xFFBA1A1A)
val BetterSaidErrorSoft = Color(0xFFFFDAD6)

val BetterSaidDarkBackground = Color(0xFF181915)
val BetterSaidDarkSurface = Color(0xFF20211D)
val BetterSaidDarkSurfaceHigh = Color(0xFF2B2C27)
val BetterSaidDarkInk = Color(0xFFF2F1EC)
val BetterSaidDarkInkSoft = Color(0xFFC8C7C1)
val BetterSaidDarkOutline = Color(0xFF5F625E)
